### ISSUE TITLE
Beefy не может найти модуль pixi.js

### ISSUE THREAD

**Issue by painkkiller** [FrontenderMagazine/introduction-to-pixijs#3]
Последовательно выполнил все шаги описанные в статье, все сработало, за исключением последнего шага, при открытии браузера по адресу http://localhost:9966/ выкидывается ошибка:
`Error: Cannot find module 'pixi.js' from 'C:\Users\PainKiller\Desktop\pixitest'
    at C:\Users\PainKiller\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\PainKiller\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\PainKiller\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\PainKiller\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\PainKiller\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\PainKiller\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)`

Pixi.js пробовал ставить и с гитхаба и просто набирая npm install -s pixi.js В обеих случаях, в папке node_modules/pixi.js самого файла с расширением js не было, пробовал закинуть его в ручную, дало тот же результат.

**Comment by iamstarkov** [comment]
@PainKKKiller попробуй ознакомиться с руководством по старту работа в ридми https://github.com/pixijs/pixi.js#setup

**Comment by painkkiller** [comment]
вообще то я его читал, примеры оттуда работают, но мне нужно именно чтобы с browserify  работало. В общем проблема только с beefy.
